[project]
name = "drone-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "opencv-python>=5.0.0.93",
    "pseyepy",
    "pygame>=2.6.1",
    "typer>=0.15.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
pseyepy = { git = "https://github.com/iqsnider/pseyepy" }

[tool.hatch.build.targets.wheel]
packages = ["src/calibration", "src/drone"]
